name = "status-worker"
workers_dev = false
account_id = "3ed51f2c99510cd7fe8fcd8ed0621a37"
compatibility_date = "2022-10-06"
main = "src/index.ts"

kv_namespaces = [
  { binding = "KV", id = "a6dc1a5965ee413ea0b110a065195649", preview_id = "" }
]

[triggers]
crons = ["* * * * *"]