name = "discord-status"
workers_dev = false
account_id = "3ed51f2c99510cd7fe8fcd8ed0621a37"
compatibility_date = "2022-10-06"
main = "src/index.ts"

kv_namespaces = [
  { binding = "KV", id = "bced06eeda5f4ac5a3348323fc2f91bc", preview_id = "" }
]

[triggers]
crons = ["*/3 * * * *"]